name: Farmer Warehouse Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: farmer_warehouse_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
          --name mysql_test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mysql-connector-python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Wait for MySQL to be ready
      run: |
        for i in {60..0}; do
          if docker exec mysql_test mysqladmin ping --host=localhost --user=root --password=password --silent; then
            echo "MySQL is ready!"
            break
          fi
          echo 'Waiting for MySQL...'
          sleep 2
        done
        if [ "$i" = 0 ]; then
          echo 'MySQL did not start in time. Printing MySQL logs...'
          docker logs mysql_test
          exit 1
        fi

    - name: Run tests with pytest
      run: |
        pytest
